language: generic

sudo: required

before_script: |
    git clone https://github.com/neovim/neovim/wiki/Building-Neovim
    cd Building-Neovim/
    make
    sudo make install
    cd ..
    curl -fLo ~/.config/.nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    mkdir ~/.SUCH-Vim
    cp -r ./* ~/.SUCH-Vim

script: |
    pwd
    sh /home/travis/build/nasim80/SUCH-Vim/run_tests_travis.sh > /dev/null
