language: generic

sudo: required

before_script: |
    sudo add-apt-repository ppa:fcwu-tw/ppa
    sudo apt-get update
    sudo apt-get install vim
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    mkdir ~/.SUCH-Vim
    cp -r ./* ~/.SUCH-Vim

script: |
    sh run_tests_travis.sh > /dev/null
