language: generic

sudo: required

before_script: |
    git clone https://github.com/vim/vim
    cd vim
    make
    sudo make install
    vim --version
    cd ..
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    mkdir ~/.SUCH-Vim
    cp -r ./* ~/.SUCH-Vim

script: |
    sh run_tests_travis.sh > /dev/null
