language: generic

sudo: required

before_script: |
    git clone https://github.com/junegunn/vader.vim.git
    git clone https://github.com/junegunn/vim-pseudocl.git
    git clone https://github.com/tpope/vim-repeat
    hg clone https://code.google.com/p/vim/
    cd vim
    # ./configure --with-features=huge --enable-rubyinterp --enable-pythoninterp
    ./configure --with-features=huge
    make
    sudo make install
    cd ..
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    mkdir ~/.SUCH-Vim
    cp -r ./* ~/.SUCH-Vim

script: |
    sh run_tests_travis.sh > /dev/null
