language: generic

sudo: required

before_script: |
    sudo apt-get install -y software-properties-common
    sudo apt-get install -y python-software-properties
    sudo add-apt-repository -y ppa:neovim-ppa/unstable
    sudo apt-get -qq update
    sudo apt-get install -y neovim
    sudo apt-get install pip
    pip install --upgrade pip
    sudo apt-get install npm
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    mkdir ~/.SUCH-Vim
    cp -r ./* ~/.SUCH-Vim

script: |
    sh run_tests_travis.sh > /dev/null
